name = "json-formatter"
compatibility_date = "2024-03-26"

kv_namespaces = [
  { binding = "800b294a9c6845878b890ca7381b7da3", id = "your_kv_namespace_id", preview_id = "your_preview_kv_namespace_id" }
] 